[package]
description = "CosmWasm integration testing for Coreum"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/CoreumFoundation/test-tube"
name = "coreum-test-tube"
version = "3.0.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = ["coreum", "test_artifacts"]

[dependencies]
base64 = "0.20.0"
cosmrs = {version = "0.14.0", features = ["cosmwasm"]}
cosmwasm-std = "1.4.0"
prost = "0.11.0"
serde = "1.0.188"
serde_json = "1.0.106"
test-tube-coreum = { version = "0.1.0", path = "../test-tube" }
thiserror = "1.0.48"
coreum-wasm-sdk = "0.2.0"

[build-dependencies]
bindgen = "0.68.1"

[dev-dependencies]
cw1-whitelist = "1.1.0"
rayon = "1.7.0"
